"""transform_to_universal_web_scraper

Revision ID: 5e1db86f4bae
Revises: 68cd2c9adc4b
Create Date: 2025-09-06 21:42:31.124781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1db86f4bae'
down_revision: Union[str, Sequence[str], None] = '68cd2c9adc4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackers', 'tracker_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackers', sa.Column('tracker_type', sa.VARCHAR(), server_default=sa.text("'gndu_result'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
