"""convert_to_url_based_scraping

Revision ID: 662db054e2c4
Revises: 5e1db86f4bae
Create Date: 2025-09-06 21:45:15.311724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662db054e2c4'
down_revision: Union[str, Sequence[str], None] = '5e1db86f4bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns with default values for existing data
    op.add_column('trackers', sa.Column('target_url', sa.String(), nullable=False, server_default='http://collegeadmissions.gndu.ac.in/studentArea/GNDUEXAMRESULT.aspx'))
    op.add_column('trackers', sa.Column('search_term', sa.String(), nullable=False, server_default='DEMO123'))
    
    # Remove server defaults after adding columns
    op.alter_column('trackers', 'target_url', server_default=None)
    op.alter_column('trackers', 'search_term', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop new columns
    op.drop_column('trackers', 'search_term')
    op.drop_column('trackers', 'target_url')
    # ### end Alembic commands ###
