"""add_tracker_type_field_for_platform

Revision ID: 68cd2c9adc4b
Revises: 98bf0d824024
Create Date: 2025-09-06 20:46:21.533355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68cd2c9adc4b'
down_revision: Union[str, Sequence[str], None] = '98bf0d824024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackers', sa.Column('tracker_type', sa.String(), nullable=False, server_default='gndu_result'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackers', 'tracker_type')
    # ### end Alembic commands ###
