"""make_application_id_nullable

Revision ID: 868302a1a3bb
Revises: 662db054e2c4
Create Date: 2025-09-07 15:59:21.240129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868302a1a3bb'
down_revision: Union[str, Sequence[str], None] = '662db054e2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackers', 'search_term')
    op.drop_column('trackers', 'target_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackers', sa.Column('target_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('trackers', sa.Column('search_term', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
